.circleci/config.yml
.gitattributes
.github/CONTRIBUTING.md
.gitignore
.scalafmt.conf
build.sbt
project/build.properties
project/plugins.sbt
sbt

C&P from zio-keeper. @mijicd please verify this.

Project setup

---

docs/overview/index.md
examples/src/main/scala/zio/logging/Examples.scala

Using correct way to provide layer to program in documentation. 
Also use `provideLayer` instead of `provideSomeLayer` as it's the only layer the program depends on

Using correct way to provide layer to program in documentation

---

build.sbt
core/src/main/scala/zio/logging/Logging.scala
core/src/test/scala/zio/logging/LoggerSpec.scala

ZIO-RC18-2 contains significant improvement of root fibers tracking which prevents memory leaks, so it'd be nice to deliver this asap.

ZIO upgrade to RC18-2

---

core/src/main/scala/zio/logging/LogAnnotation.scala
slf4j/src/main/scala/zio/logging/slf4j/Slf4jLogger.scala

Hi
I'm not sure if I understood the library structure correctly but this seemed to be a possible solution.  What do you think?

Use the Throwable version of slf4j logger methods

---

core/src/main/scala/zio/logging/LogAppender.scala

This is an idea I brought up in the last PR. Basically the idea is to not die with a defect if logging to a file fails. Instead what it does is print the I/O exception to stderr, and then supresses the exception for each subsequent failure. This is to prevent log spam because if one `write` failed, it's not particularly helpful to know that the 2nd, 3rd, etc. also failed with the same exception.
This is just an alternate idea to terminating with ZIO.Die. I could see there being a case for making different configurable modes of failure (like `Die`, `Warn`, `Ignore`). And I don't have strong opinions about what the default should be. As long an option is there, it would satisfy what I'm trying to do.
For an additional reference, log4j seems to have two modes with the `ignoreExceptions` …

Modify failure mode for file I/O exceptions

---

docs/overview/index.md

I was learning from tutorial and noticed this error.

Rename level to logLevel

---

docs/overview/index.md
slf4j-bridge/src/main/scala/org/slf4j/impl/ZioLoggerFactory.scala
slf4j-bridge/src/main/scala/zio/logging/slf4j/bridge/package.scala
slf4j-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeSpec.scala

Implements @jdegoes 's recommended changes for https://github.com/zio/zio-logging/pull/202

Renames and cleanup for the SLF4j bridge

---

.github/workflows/ci.yml
.gitignore

Prevent issues with Website in CI

---

build.sbt

This is causing issues in scala 3 builds in projects that use zio-logging

Remove scala-collection-compat CrossVersion modifier

---

core/shared/src/main/scala/zio/logging/Logger.scala
core/shared/src/main/scala/zio/logging/Logging.scala
core/shared/src/main/scala/zio/logging/log.scala
slf4j-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeSpec.scala

Add Warn level logging with cause

---

build.sbt
core/jvm/src/test/scala/zio/logging/LogFormatSpec.scala
core/shared/src/main/scala/zio/logging/LogFormat.scala
core/shared/src/main/scala/zio/logging/package.scala
slf4j-bridge/src/main/scala/org/slf4j/impl/ZioLoggerFactory.scala
slf4j/src/main/scala/zio/logging/slf4j/SLF4J.scala

Hi all,
This pull request provides some updates to make ZIO Logging work with ZIO 2.0.0 final.
Hope this is useful!

update ZIO to 2.0 final.

---

core/shared/src/main/scala/internal/JsonEscape.scala
core/shared/src/main/scala/internal/LogAppender.scala

@jdegoes Do you mean something like this?

Try to optimize json encoding a bit

---

core/shared/src/main/scala/zio/logging/package.scala

Fix file loggers

---

core/jvm/src/test/scala/zio/logging/LogFormatSpec.scala
core/shared/src/main/scala/zio/logging/LogFormat.scala

colored and default LogFormat with cause if exists

---

core/jvm/src/test/scala/zio/logging/JsonLogFormatSpec.scala
core/shared/src/main/scala/zio/logging/internal/LogAppender.scala

Solves https://github.com/zio/zio-logging/issues/496

Support numeric json field

---

slf4j-bridge/src/main/scala-2/org/slf4j/impl/ZioLogger.scala
slf4j-bridge/src/main/scala-3/org/slf4j/impl/ZioLogger.scala
slf4j-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeSpec.scala

slf4j bridge - null Throwable as empty Cause

---

core/jvm/src/test/scala/zio/logging/LogFormatSpec.scala
core/shared/src/main/scala/zio/logging/LogFormat.scala
docs/overview/index.md
examples/src/main/resources/logback.xml
examples/src/main/scala/zio/logging/example/Slf4jSimpleApp.scala
jpl/src/main/scala/zio/logging/backend/JPL.scala
jpl/src/test/scala/zio/logging/backend/JPLSpec.scala
slf4j/src/main/scala/zio/logging/slf4j/SLF4J.scala
slf4j/src/test/resources/logback-test.xml
slf4j/src/test/scala/zio/logging/backend/SLF4JSpec.scala

slf4j log marker 
slf4j default log format with excluded annotations for logger name and log marker
jpl default log format with excluded annotation for logger name
LogFormat annotations with exclude by keys
Fixes: #520

slf4j markers

---

docs/overview/index.md
examples/src/test/scala/zio/logging/example/LoggingSpec.scala

test example

---

.github/workflows/ci.yml
project/BuildHelper.scala
project/build.properties
project/plugins.sbt

scala 2.13.10

---

docs/jpl.md
docs/slf4j.md
docs/slf4j_bridge.md
docs/testing.md

fix for duplicated page titles

documentation titles fix

---

slf4j/src/main/scala/zio/logging/slf4j/SLF4J.scala
slf4j/src/test/scala/zio/logging/backend/SLF4JSpec.scala

slf4j label format fix

---

core/jvm/src/test/scala/zio/logging/MetricsSpec.scala

Added spec for traceCounter in MetricsSpec.scala

added spec for traceCounter

---

build.sbt
core/jvm/src/test/scala/zio/logging/MetricsSpec.scala

added the missing traceCounter log

added missing traceCounter log in MetricSpec.scala

---

build.sbt
core/jvm/src/test/scala/zio/logging/MetricsSpec.scala
core/jvm/src/test/scala/zio/logging/test/TestService.scala

Added implementation for testTrace variable in TestService.scala file

Added implementation for testTrace variable

---

core/jvm/src/test/scala/zio/logging/JsonGenerator.scala
core/jvm/src/test/scala/zio/logging/JsonLogFormatSpec.scala
core/jvm/src/test/scala/zio/logging/internal/JsonValidatorSpec.scala
core/shared/src/main/scala/zio/logging/internal/JsonValidator.scala
core/shared/src/main/scala/zio/logging/internal/LogAppender.scala
docs/console-logger.md
examples/core/src/main/scala/zio/logging/example/ConsoleJsonApp.scala

This is the WIP implementation of stringIsJson method.
Could you have a look and see if this makes sense please?
Some remarks:
- I am using custom small boolean stack to keep information about nested structure (current position inside array or inside an object). The requirement was to make this zero-allocation method which I believe is true here but I am using custom small sized boolean stack implemented with plain Long value to avoid heap allocation. Info I found on the net was contradictory on whether array can be allocated on stack or not. I tried few things but failed to make it stack allocated. In the end I decided for a Long value where bits represent state - 0 (inside array), 1 (inside object) which could be an overkill just to avoid heap allocation but I left it anyways :D The …

Implement stringIsJson method

---

core/jvm/src/test/scala/zio/logging/JsonLogFormatSpec.scala
core/shared/src/main/scala/zio/logging/internal/LogAppender.scala

json logger - null value for json attribute if value result is empty

---

README.md

readme - fix contributing and code of conduct links
