- core/src/main/scala/zio/logging/Logger.scala
- slf4j/src/main/scala/zio/logging/slf4j/Slf4jLogger.scala
In log level configuration, e.g. logback, one refers to a logger name in order to determine log levels and other properties. It is very useful to be able to determine a global logger name in the moment of its creation. This PR addresses just that, by adding convenience methods to `Logger` and `Slf4jLogger`.
> Add convenience methods to create default-named loggers

- core/src/main/scala/zio/logging/LogAnnotation.scala
- core/src/main/scala/zio/logging/Logging.scala
- core/src/main/scala/zio/logging/log.scala
- examples/src/main/scala/zio/logging/Examples.scala
this is change how we handle cause and throwable. before we handle this in `log` object but logger should have flexibility how to render error. Moreover that fix logger inference name when slf4j logger is used.
> Fix name of logger

- build.sbt
- docs/overview/index.md
- examples/src/main/resources/logback.xml
- examples/src/main/scala/zio/logging/Slf4jMdc.scala
- slf4j/src/main/scala/zio/logging/slf4j/Slf4jLogger.scala
- slf4j/src/test/resources/logback-test.xml
- slf4j/src/test/scala/zio/logging/slf4j/Slf4jLoggerTest.scala
- slf4j/src/test/scala/zio/logging/slf4j/TestAppender.scala
Added an implementation of slf4j logger that puts a defined set of annotations from the LogContext into MDC logging context.
> slf4j logger with annotations on mdc context

- build.sbt
- core/src/main/scala/zio/logging/LogDatetimeFormatter.scala
- core/src/main/scala/zio/logging/LogLevel.scala
- core/src/main/scala/zio/logging/LogWriter.scala
- core/src/main/scala/zio/logging/Logging.scala
AddedColoredLogWriter using ANSI colors to make logs readable.
Make it as default console logger.
Moved previous default console writer to SimpleConsoleLogWriter.
Also changed logLevel render names  lowercase to not yelling at me.
Before:
After:
> Make console logger nice and beauty

- core/src/main/scala/zio/logging/Logger.scala
A lot of times, an effect should be executed only for logging purposes. This can cause performance issues even when the logging is turned off since the effect will still get evaluated.
```scala
for {
f <- foo
b <- bar
_ <- log.debug(b) // b is needed only for logging purposes
} yield f
```
```scala
for {
f <- foo
_ <- log.debug(bar) // bar get's evaluated only when LogLevel is "debug"
} yield f
```
> Lazy Logging

- core/src/main/scala/zio/logging/LogAppender.scala
- core/src/main/scala/zio/logging/LogLevel.scala
- core/src/main/scala/zio/logging/Logger.scala
To stay consistent with the other ZIO projects. Also it makes reading the signatures easier. For example, you can easily see the ZLayer can fail with a Throwable and so on without looking at the implementation itself.
> Explicit type annotations to public members

- core/src/main/scala/zio/logging/LogAppender.scala
- core/src/main/scala/zio/logging/LogWriter.scala
- core/src/main/scala/zio/logging/Logging.scala
I noticed there's a `file` LogAppender and I wanted to use it, but it didn't have a constructor in `Logging`. It looks like it was still a work in progress. Here's my attempt at finishing it, as well as adding an async file logger which does two things:
- Return to the caller as quickly as possible (the "write" is just an enqueuing operation)
- Makes flushing more efficient by batching them (the batch size is configurable)
A few other things:
- `LogAppender.file` wasn't inserting a newline at the end unlike `LogAppender.console`. This means the output would be on a single line. And since `BufferedWriter` flushes on newline, flushing wasn't happening properly.
- I added LogLevel filtering to both `file` and `fileAsync`
- I changed the filename param to be a `Path` to be more consistent …
> Add async file logging and more features to file appender

- slf4j/src/main/scala/zio/logging/slf4j/Slf4jLogger.scala
- slf4j/src/test/scala/zio/logging/slf4j/Slf4jLoggerTest.scala
Currently makeWithAnnotationsAsMdc is opt-in. You need to specify all LogAnnotations that should be output as MDC beforehand. This change creates a variant where all LogAnnotations will be output in the MDC unless opted-out by an exclusion list.
> Add an opt-out makeWithAnnotationsAsMdc variant

- build.sbt
- docs/overview/index.md
- slf4j-bridge/src/main/java/org/slf4j/impl/StaticLoggerBinder.java
- slf4j-bridge/src/main/scala/org/slf4j/impl/StaticMDCBinder.scala
- slf4j-bridge/src/main/scala/org/slf4j/impl/StaticMarkerBinder.scala
- slf4j-bridge/src/main/scala/org/slf4j/impl/ZioLogger.scala
- slf4j-bridge/src/main/scala/org/slf4j/impl/ZioLoggerFactory.scala
- slf4j-bridge/src/main/scala/zio/logging/slf4j/bridge/package.scala
- slf4j-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeSpec.scala
This PR adds a new module called `zio-logging-slf4j-bridge`, which is the "opposite" of the existing SLF4j support, registering `zio-logging` as an SLF4j provider. 
With this third party libraries logging through SLF4j can log through zio-logging without the need to a third party slf4j implementation.
This is good for reducing dependencies and simplify the whole logging stack of services.
For example we are using this for mixing in sttp and Netty logs to the zio-logging log stream of a service.
Easy filtering configuration makes this much more usable, a proposed solution for that is coming in another PR.
> Slf4j bridge

- slf4j/src/main/scala/zio/logging/slf4j/Slf4jLogger.scala
Added logging guards to prevent log message evaluation if current logger is disabled.
Currently if you have a potentially expensive interpolated `String` like:
```scala
log.debug(s"Pushing: $datums")
```
where `$datums`'s `toString` is an expensive operation it gets evaluated even if the log level is disabled. This evaluation takes place at the boundary between Scala (ZIO Logging) and Java (SLF4J Logging).
This PR prevents that by setting logging guards before SLF4J Logging invocation, making the operations in ZIO side truly lazy.
> Ensure log message laziness in Slf4jLogger with logging guards

- build.sbt
- core/jvm/src/test/scala/zio/logging/LogFormatSpec.scala
- core/shared/src/main/scala/zio/logging/LogFormat.scala
- core/shared/src/main/scala/zio/logging/package.scala
- project/plugins.sbt
- slf4j/src/main/scala/zio/logging/slf4j/SLF4J.scala
Hi!
I was playing around with `zio-logging` and its `slf4j ` support over the weekenad  and noticed that the latest changes from `ZIO 2.0.0-RC3` have not been accounted for in `zio-logging` yet.
This commit upgrade the ZIO version to `ZIO 2.0.0-RC3` with the necessary code adjustments.
Using the commit above this worked nicely for me:
```
package zio2.testapp
import zio.{LogLevel, RuntimeConfigAspect, ZEnv, ZIO, ZLogger}
object TestApp extends zio.ZIOAppDefault {
def slf4jLoggerAspect: RuntimeConfigAspect = {
zio.logging.backend.SLF4J.slf4j(LogLevel.Info)
}
override def run: ZIO[ZEnv, Any, Any] = {
for {
config <- ZIO.runtimeConfig.map(c => c.copy(logger = ZLogger.none) @@ slf4jLoggerAspect) // reset logger and add slf4j logger
_      <- ZIO.setRuntimeConfig(config)
r      <- ZIO.log("ZIO …
```
> Upgrade to ZIO 2.0.0-RC3

- core/shared/src/main/scala/zio/logging/LogFormat.scala
This PR adds `annotations` which include all annotations in the `LogFormat`.
Also adds `span` and `spans` to include spans in the `LogFormat`.
> LogFormat for annotations and spans

- slf4j-bridge/src/main/scala-2/org/slf4j/impl/ZioLogger.scala
- slf4j-bridge/src/main/scala-3/org/slf4j/impl/ZioLogger.scala
- slf4j-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeSpec.scala
slf4j bridge message format fix: #482
slf4j using `{}` as placeholder
https://www.tutorialspoint.com/slf4j/slf4j_parameterized_logging.htm
> slf4j bridge message format

- .github/workflows/ci.yml
- .github/workflows/site.yml
used jdk11, because java system logger (jpl) was introduced in jdk9
> ci publish fixes - jdk11

- slf4j-bridge/src/main/java/org/slf4j/helpers/ZioLoggerBase.java
- slf4j-bridge/src/main/scala-2/org/slf4j/impl/ZioLogger.scala
- slf4j-bridge/src/main/scala-3/org/slf4j/impl/ZioLogger.scala
- slf4j-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeSpec.scala
Current `org.slf4j.impl.ZioLogger` doesn't implement `Logger#getName` that causes a silent failure when using Netty, which rejects slf4j loggers without name.
> Give proper logger name to SLF4J bridge

- slf4j-bridge/src/main/scala/org/slf4j/impl/StaticMarkerBinder.scala
- slf4j-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeSpec.scala
I noticed this issue when using ZIO with Akka and attempted to route Akka logs via the `slf4j-bridge`. Akka calls `MarkerFactory.getIMarkerFactory`, which throws an exception in the existing implementation.
> Fix StaticMarkerBinder implementation in slf4j-bridge

- project/BuildHelper.scala
java classes (slf4j-bridge) was not released with 1.8
> release java platform fix

- build.sbt
- core/jvm/src/test/scala/zio/logging/MetricsSpec.scala
- core/shared/src/main/scala/zio/logging/package.scala
- docs/metrics.md
- docs/sidebars.js
- examples/src/main/scala/zio/logging/example/MetricsApp.scala
- examples/src/main/scala/zio/logging/example/SimpleApp.scala
one of the zio logging related questions was: how to add counter/metric for error logs
As ZIO core supporting multiple loggers, this logging metrics collector is implemented as specific `ZLogger` 
which is responsible just for collecting metrics of all logs - `ZIO.log*` functions. (thanks to @vigoo for this idea)
metrics in form of counter for each log level, metric name:
zio_logger_${level.label.toLowerCase}_total
for example for LogLevel.Error: zio_logger_error_total
alternative solution for counter definition could be:
common metric name, for example zio_logger_log_total
log level in metric tags
> Log Metrics

- slf4j-bridge/src/main/scala-2/org/slf4j/impl/ZioLogger.scala
- slf4j-bridge/src/main/scala-3/org/slf4j/impl/ZioLogger.scala
- slf4j-bridge/src/main/scala/zio/logging/slf4j/bridge/Slf4jBridge.scala
- slf4j-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeSpec.scala
fixes: #598
in case of sl4j-bridge reimplementation for zio-2
`ZIO.logSpan(name)` was used, (also probably at time of reimplementation, some things in relation to zio-2 logging design, was not clear)
in zio-1 version `log.locally(LogAnnotation.Name(nameList))(f)`
considering #598 and also current implementation of zio-logging, LogAnnotation is probably better way to propagate logger name
there is also a question if we should have `ZIO.logSpan(name)` for backward compatibility
> slf4j bridge - logger name annotation

- core/jvm/src/test/scala/zio/logging/MetricsSpec.scala
- core/shared/src/main/scala/zio/logging/package.scala
- docs/metrics.md
The current impl. creates many metrics, which is not idiomatic. They are all the same metric with different notions. Therefore I propose to use labels instead with only one counter.
Also I think being forced to use a certain metric name is not good, since orgs might enforce naming conventions.
I remember, that we have the option for custom naming in other zio metrics too. I think it was zio-http.
> Idiomatic log metrics with customizable naming

- examples/src/main/scala/zio/logging/example/Slf4jFailureApp.scala
- slf4j/src/main/scala/zio/logging/slf4j/SLF4J.scala
Fixes: #616 
it is look like that program will end sooner then slf4j log system is initialised and message logged, in cases when failure is first log in application
adding `LoggerFactory.getLogger("zio-slf4j-logger")` to slf4j layer should invoke initialisation of slf4j log system
> slf4j backend - invoke slf4j initialisation

- slf4j/src/main/scala/zio/logging/slf4j/SLF4J.scala
We had an issue with double logging due to the presence of 2 such layers in our application, and it took a while to discover the root cause. Such a documentation could help other devs in the same situation.
> Document the usage of `Slf4j.slf4j` layer

- build.sbt
https://github.com/zio/zio-logging/actions/runs/4146843375/jobs/7173088282
error [SonatypeClient]     Failed: javadoc-staging, failureMessage:Missing: no javadoc jar found in folder '/dev/zio/zio-logging-slf4j2-bridge_2.11/2.1.9
> slf4j2 javadoc fix

- .github/workflows/ci.yml
- build.sbt
- core/shared/src/main/scala/zio/logging/LogAnnotation.scala
- project/BuildHelper.scala
- project/build.properties
- project/plugins.sbt
According to release notes of ZIO 1.0.18:
> All Scala 3 users and downstream libraries are advised to update to ZIO 1.0.18 or newer and release newly recompiled versions to avoid stale Tags generated by older versions of izumi-reflect from surfacing https://github.com/zio/zio/issues/7489 on Scala 3.
> update zio to 1.0.18

- build.sbt
During ZIO update it was incorrectly assumed that conflict of suffixes `_2.13`, `_3` was related to `scala-collection-compat`. In fact, it was fixed by dropping `!` for sbt command for Scala 3. Current build is leading to build error in dependent projects.
```
[error] Modules were resolved with conflicting cross-version suffixes in ProjectRef(uri("file:/"), "root"):
[error]    org.scala-lang.modules:scala-collection-compat _2.13, _3
[error] java.lang.RuntimeException: Conflicting cross-version suffixes in: org.scala-lang.modules:scala-collection-compat
```
Workaround is:
```
("dev.zio" %% "zio-logging-slf4j" % "0.5.15").exclude("org.scala-lang.modules", "scala-collection-compat_2.13")
```
> fix scala-collection-compat

- project/BuildHelper.scala
It is strange that it is working without a fix, so probably these cases are not needed at all.
> fix scala 3 version checks in build

- core/jvm/src/test/scala/zio/logging/LogFilterSpec.scala
- core/shared/src/main/scala/zio/logging/LogFilter.scala
- docs/log-filter.md
#612
I implemented `**` (any number of paths) and `*` (any (partial) path) within the existing LogFilter path structure `List[String]`. 
I think this could be optimized if the LogFilters were used in a nested map-like structure. 
Another way would be the use regex.
> Feature #612 - implement LogFilter glob-like wildcard support

- docs/slf4j1-bridge.md
- docs/slf4j2-bridge.md
- examples/core/src/main/scala/zio/logging/example/SimpleApp.scala
- examples/slf4j2-bridge/src/main/scala/zio/logging/example/Slf4jBridgeExampleApp.scala
- project/MimaSettings.scala
- slf4j-bridge/src/main/scala/org/slf4j/impl/ZioLoggerFactory.scala
- slf4j-bridge/src/main/scala/zio/logging/slf4j/bridge/Slf4jBridge.scala
- slf4j-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeExampleApp.scala
- slf4j-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeSpec.scala
- slf4j2-bridge/src/main/scala/zio/logging/slf4j/bridge/Slf4jBridge.scala
- slf4j2-bridge/src/main/scala/zio/logging/slf4j/bridge/ZioLoggerRuntime.scala
- slf4j2-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeExampleApp.scala
- slf4j2-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeSpec.scala
`FiberRefs` propagation using `ThreadLocal`
> Slf4j bridge - fiber propagation

- core/jvm/src/test/scala/zio/logging/LogAnnotationSpec.scala
- core/shared/src/main/scala/zio/logging/LogAnnotation.scala
- core/shared/src/main/scala/zio/logging/package.scala
improved composition of multiple zio-logging `LogAnnotation` - to update logContext  just once
> Log annotations optimisations

- slf4j-bridge/src/main/scala/zio/logging/slf4j/bridge/Slf4jBridge.scala
- slf4j-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeSpec.scala
- slf4j2-bridge/src/main/scala/zio/logging/slf4j/bridge/Slf4jBridge.scala
- slf4j2-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeSpec.scala
add init log for slf4j bridge
more like in case of zio app, where there is just one initialisation it is not issue
but in case of tests, and multiple parallel initialisations, it is making issues like:
```
- Slf4jBridge - parallel init
Exception in thread "zio-fiber-91,78" java.lang.ClassCastException: class org.slf4j.helpers.SubstituteLoggerFactory cannot be cast to class zio.logging.slf4j.bridge.LoggerFactory (org.slf4j.helpers.SubstituteLoggerFactory and zio.logging.slf4j.bridge.LoggerFactory are in unnamed module of loader sbt.internal.LayeredClassLoader @3c6460fa)
at zio.logging.slf4j.bridge.Slf4jBridge$.$anonfun$layer$3(Slf4jBridge.scala:43)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at zio.logging.slf4j.bridge.Slf4jBridge.layer(Slf4jBridge.scala:39) …
```
> slf4j bridge - init lock

- core/shared/src/main/scala/zio/logging/LogFilter.scala
- docs/slf4j1-bridge.md
- docs/slf4j2-bridge.md
- examples/slf4j2-bridge/src/main/scala/zio/logging/example/Slf4jBridgeExampleApp.scala
- slf4j-bridge/src/main/java/org/slf4j/helpers/ZioLoggerBase.java
- slf4j-bridge/src/main/scala/org/slf4j/impl/LoggerRuntime.scala
- slf4j-bridge/src/main/scala/org/slf4j/impl/ZioLogger.scala
- slf4j-bridge/src/main/scala/org/slf4j/impl/ZioLoggerFactory.scala
- slf4j-bridge/src/main/scala/zio/logging/slf4j/bridge/Slf4jBridge.scala
- slf4j-bridge/src/main/scala/zio/logging/slf4j/bridge/ZioLoggerRuntime.scala
- slf4j-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeExampleApp.scala
- slf4j-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeSpec.scala
- slf4j2-bridge/src/main/java/zio/logging/slf4j/bridge/Logger.java
- slf4j2-bridge/src/main/java/zio/logging/slf4j/bridge/LoggerFactory.java
- slf4j2-bridge/src/main/java/zio/logging/slf4j/bridge/LoggerRuntime.java
- slf4j2-bridge/src/main/scala/zio/logging/slf4j/bridge/Slf4jBridge.scala
- slf4j2-bridge/src/main/scala/zio/logging/slf4j/bridge/ZioLoggerRuntime.scala
- slf4j2-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeExampleApp.scala
- slf4j2-bridge/src/test/scala/zio/logging/slf4j/bridge/Slf4jBridgeSpec.scala
slf4j Logger  - `is<Level>Enabled` implementation using `zio.logging.LogFilter` (based on logger name, and given level)
fixes: #809
> slf4j bridge - filter

- .github/workflows/ci.yml
- build.sbt
- project/Versions.scala
fixes: #846
removed java 8 support, as zio 2.1.+ [require jdk 11](https://github.com/zio/zio-logging/actions/runs/9046652250/job/24857704028)
```
[error] java.lang.UnsupportedClassVersionError: zio/internal/MutableQueueFieldsPadding has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
[error] 	at java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
```
> zio 2.1.1, removed java 8 support

- .github/workflows/ci.yml
- README.md
- build.sbt
- docs/jul-bridge.md
- docs/sidebars.js
- docs/slf4j2-bridge.md
- examples/jul-bridge/src/main/scala/zio/logging/example/JULBridgeExampleApp.scala
- jul-bridge/src/main/scala/zio/logging/jul/bridge/JULBridge.scala
- jul-bridge/src/main/scala/zio/logging/jul/bridge/ZioLoggerRuntime.scala
- jul-bridge/src/test/scala/zio/logging/jul/bridge/JULBridgeSpec.scala
Useful for `zio-telemetry` - Java OpenTelemetry library is using JUL (https://togithub.com/open-telemetry/opentelemetry-java/issues/5715)
> Implement java.util.logging bridge

- core/jvm/src/test/scala/zio/logging/AppendLoggerNameSpec.scala
- core/shared/src/main/scala/zio/logging/package.scala
We are upgrading from ZIO 1, where the previous version of zio.logging appended the logger name to the existing logger name. In the new version, it replaces it. This PR suggests introducing a new aspect, appendLoggerName, to append a string to the existing logger name.
Our codebase relies on setting the logger name. For example, when our RPC framework receives an incoming message, we add the service name and method name to the logger name.
> Add appendLoggerName aspect

- build.sbt
- core/shared/src/test/scala/zio/logging/JsonLogFormatSpec.scala
- core/shared/src/test/scala/zio/logging/LogFilterSpec.scala
- core/shared/src/test/scala/zio/logging/LogFormatSpec.scala
- core/shared/src/test/scala/zio/logging/LogGroupSpec.scala
- core/shared/src/test/scala/zio/logging/LoggerNameExtractorSpec.scala
- project/Versions.scala
zio 2.1.14, test fixes (Trace.unapply changed, and there were issues with line 0)
> zio 2.1.14, test fixes

- core/shared/src/main/scala/zio/logging/LogFormat.scala
- core/shared/src/main/scala/zio/logging/LoggerNameExtractor.scala
> optimisation in relation to Trace parse
